### PR TITLE
The building guide of development environment for software developer

### PR DESCRIPTION
**Pull request by hiroakit**
## Purpose

* Ref #527
* This PR has a draft document. 
I would like to collect the information based on it.

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[X] Documentation content changes
[ ] Other... Please describe:
```

## How to Test

None.

## What to Check
Verify that the following are valid
* This document's file name, file path
* OS, IDE, SDK version

## Other Information

This document is draft.
Any comment are welcome.

### CODE REVIEW

**Comment by hiroakit** [comment]
Dear @kazumihirose san, @changeworld san, 

I'm sorry to bother you when you are busy.
I wrote a building guide of development environment (`doc/Developer.md`) from the following point of views:

- Android
- iOS
- Server

Would you like to review my PR, please?.

Maybe, i think my document has a problem.
It's in the hope that it would be a little better than having nothing.

In addition, i host Azure Functions and Azure Cosmos for development, 
and i got that connect to the environment with the Android & iOS app.

**Comment by changeworld** [comment]
@hiroakit 
Thank you for your great contribution!

**Comment by hiroakit** [comment]
Thank you!
It's my pressure.

How is His Highness?
I'm concerned.

I'll continue to send PR.

**Comment by hiroakit** [comment]
Dear @changeworld san, @kazumihirose san, 

Thank you for mergeing my PR.
But, i couldn't find merge commit of the PR now.

Would you check it, please?

**Comment by sushichop** [comment]
@hiroakit 
Me too unfortunately. I couldn't find doc/Developer.md on [master branch](https://github.com/Covid-19Radar/Covid19Radar/tree/7e0910d80b39d730b5e0a61c6c9b99fe6277cfa7). 
Now I want to add information based on `doc/Developer.md`.

**Pull request merged**
