### PR TITLE
Convert ic_launcher.png to webp

### PR DESCRIPTION
**Pull request by TentaShion**
## Purpose
To reduce ic_launcher size.
PR for #511 

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* App icon is displayed without problems

## Other Information

filename | before size[kb] | after size[kb] | difference[kb]
--- | --- | --- | ---
mipmap-hdpi/ic_launcher | 4.15 | 1.02 | -3.1
mipmap-mdpi/ic_launcher | 2.36 | 0.74 | -1.6
mipmap-xhdpi/ic_launcher | 5.54 | 1.39 | -4.2
mipmap-xxhdpi/ic_launcher | 10.8 | 2.06 | -8.7
mipmap-xxxhdpi/ic_launcher | 14.2 | 3.02 | -11.12

### CODE REVIEW

**Comment by changeworld** [comment]
@noriji 
デザイン品質に関わると思うので、確認していただけますか？

**Comment by shogo82148** [comment]
It looks that converted WebP files are lossy format.

```
$ file Covid19Radar/Covid19Radar.Android/Resources/mipmap-xxxhdpi/ic_launcher.webp
Covid19Radar/Covid19Radar.Android/Resources/mipmap-xxxhdpi/ic_launcher.webp: RIFF (little-endian) data, Web/P image, VP8 encoding, 192x192, Scaling: [none]x[none], YUV color, decoders should clamp
```

```
$ compare -metric PSNR ~/Downloads/ic_launcher.png Covid19Radar/Covid19Radar.Android/Resources/mipmap-xxxhdpi/ic_launcher.webp NULL:
34.9402%
```

I think ic_launcher file are very important images, so they should be encoded lossless format.

**Comment by TentaShion** [comment]
Thank you for the review.
I didn't use ```-define webp:lossless=true```, so lossy format.
With this option, I looked like there was no loss.

### Target: mipmap-xxxhdpi/ic_launcher.png
| | original | no-option | with option
--- | :---: | :---: | :---:
size[kb] | 14.20 | 3.02 | 8.06
diff | - | no-option | with option

* I got a diff using this command.
```
compare ic_launcher.png mipmap-xxxhdpi/ic_launcher.webp diff.png
```

### Reference
* [ImageMagick - WebP Encoding Options](https://imagemagick.org/script/webp.php)

**Comment by TentaShion** [comment]
I replaced to lossless WebP at ed3515a.
I use [ImageMagick] like this.

``` bash
# lossless=false
magick mipmap-hdpi/ic_launcher.png -define webp:lossless=false mipmap-hdpi/ic_launcher.webp
compare mipmap-hdpi/ic_launcher.png mipmap-hdpi/ic_launcher.webp mipmap-hdpi/before.png

# lossless=true
magick mipmap-hdpi/ic_launcher.png -define webp:lossless=true mipmap-hdpi/ic_launcher2.webp
compare mipmap-hdpi/ic_launcher.png mipmap-hdpi/ic_launcher2.webp mipmap-hdpi/after.png
```


## Result
hdpi | original | WebP(lossless=false)<br />8d71f88 | WebP(lossless=true)<br />ed3515a
--- | :---: | :---: | :---:
Image Size[KB] | 4.15 | 1.09 | 2.35
Difference from the original | - | before | after


mdpi | original | WebP(lossless=false)<br />8d71f88 | WebP(lossless=true)<br />ed3515a
--- | :---: | :---: | :---:
Image Size[KB] | 2.36 | 0.79 | 1.39
Difference from the original | - | before | after


xhdpi | original | WebP(lossless=false)<br />8d71f88 | WebP(lossless=true)<br />ed3515a
--- | :---: | :---: | :---:
Image Size[KB] | 5.54 | 1.49 | 3.05
Difference from the original | - | before | after


xxhdpi | original | WebP(lossless=false)<br />8d71f88 | WebP(lossless=true)<br />ed3515a
--- | :---: | :---: | :---:
Image Size[KB] | 10.84 | 2.25 | 5.91
Difference from the original | - | before | after


xxxhdpi | original | WebP(lossless=false)<br />8d71f88 | WebP(lossless=true)<br />ed3515a
--- | :---: | :---: | :---:
Image Size[KB] | 14.20 | 3.02 | 8.06
Difference from the original | - | before | after


[ImageMagick]: https://imagemagick.org/index.php

**Comment by kazumihirose** [comment]
This is not a COCOA code operated by the Ministry of Health, Labor and Welfare.
I am very sorry, but I would appreciate if the Ministry of Health, Labor and Welfare (COCOA) could issue/PR again.
Kindly thank you.

**Pull request closed without merging**
